---

- hosts: all 
  become: true 
  tasks: 

  - name: remove apache2 package 
    apt: 
      name: apache2
      state: absent

  - name: remove php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
